[project]
name = "prediction-market-qts"
version = "0.1.0"
description = "Quantitative trading strategy for prediction markets"
readme = "README.md"
authors = [
    { name = "Antonio Braz", email = "antonio@torreaobraz.com" }
]
requires-python = ">=3.14"
dependencies = [
    "kaleido>=1.2.0",
    "plotly>=6.5.1",
    "polars[rt64]>=1.36.1",
]

[build-system]
requires = ["uv_build>=0.10.6,<0.11.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "ipykernel>=7.1.0",
    "nbformat>=5.10.4",
    "pytest>=9.0.2",
    "ruff>=0.14.13",
    "ty>=0.0.12",
]
