[project]
name = "prediction-market-qts"
version = "0.1.0"
description = "Quantitative trading strategy for prediction markets"
readme = "README.md"
authors = [
    { name = "Antonio Braz", email = "antonio@torreaobraz.com" }
]
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.10.6,<0.11.0"]
build-backend = "uv_build"
